/// Flutter icons SystemIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SystemIcons
///      fonts:
///       - asset: fonts/SystemIcons.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class SystemIcons {
  SystemIcons._();

  static const _kFontFam = 'SystemIcons';
  static const String? _kFontPkg = null;

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData services = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_scan = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_1 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drawer = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
